export type Restaurant = {
  id: number;
  name: string;
  cuisineId: number;
  priceRange: string;
  rating: number;
  delivery: boolean;
  dietaryOptionIds: number[];
};

export const restaurants: Restaurant[] = [
  {
    id: 1,
    name: "The Golden Spoon",
    cuisineId: 9,
    priceRange: "$$$",
    rating: 4.5,
    delivery: true,
    dietaryOptionIds: [3, 1],
  },
  {
    id: 2,
    name: "Sushi Paradise",
    cuisineId: 10,
    priceRange: "$$$$",
    rating: 4.8,
    delivery: false,
    dietaryOptionIds: [1],
  },
  {
    id: 3,
    name: "Taco Fiesta",
    cuisineId: 13,
    priceRange: "$",
    rating: 4.2,
    delivery: true,
    dietaryOptionIds: [3, 2],
  },
  {
    id: 4,
    name: "Le Petit Bistro",
    cuisineId: 4,
    priceRange: "$$$$",
    rating: 4.7,
    delivery: false,
    dietaryOptionIds: [3],
  },
  {
    id: 5,
    name: "Dragon Wok",
    cuisineId: 3,
    priceRange: "$$",
    rating: 4.3,
    delivery: true,
    dietaryOptionIds: [3, 2, 1],
  },
  {
    id: 6,
    name: "Burger Haven",
    cuisineId: 1,
    priceRange: "$$",
    rating: 4.0,
    delivery: true,
    dietaryOptionIds: [3],
  },
  {
    id: 7,
    name: "Spice Route",
    cuisineId: 8,
    priceRange: "$$",
    rating: 4.6,
    delivery: true,
    dietaryOptionIds: [3, 2, 1],
  },
  {
    id: 8,
    name: "Athens Grill",
    cuisineId: 6,
    priceRange: "$$$",
    rating: 4.4,
    delivery: false,
    dietaryOptionIds: [3, 1],
  },
  {
    id: 9,
    name: "Bangkok Street Food",
    cuisineId: 18,
    priceRange: "$",
    rating: 4.5,
    delivery: true,
    dietaryOptionIds: [3, 2],
  },
  {
    id: 10,
    name: "Seoul Kitchen",
    cuisineId: 11,
    priceRange: "$$",
    rating: 4.7,
    delivery: true,
    dietaryOptionIds: [1],
  },
  {
    id: 11,
    name: "Pizza Perfetto",
    cuisineId: 9,
    priceRange: "$$",
    rating: 4.1,
    delivery: true,
    dietaryOptionIds: [3],
  },
  {
    id: 12,
    name: "Steakhouse Prime",
    cuisineId: 1,
    priceRange: "$$$$",
    rating: 4.9,
    delivery: false,
    dietaryOptionIds: [1],
  },
  {
    id: 13,
    name: "Vegan Delight",
    cuisineId: 20,
    priceRange: "$$",
    rating: 4.6,
    delivery: true,
    dietaryOptionIds: [3, 2, 1],
  },
  {
    id: 14,
    name: "Mediterranean Breeze",
    cuisineId: 12,
    priceRange: "$$$",
    rating: 4.5,
    delivery: false,
    dietaryOptionIds: [3, 2],
  },
  {
    id: 15,
    name: "Ramen House",
    cuisineId: 10,
    priceRange: "$$",
    rating: 4.4,
    delivery: true,
    dietaryOptionIds: [3],
  },
  {
    id: 16,
    name: "BBQ Smokehouse",
    cuisineId: 1,
    priceRange: "$$$",
    rating: 4.3,
    delivery: true,
    dietaryOptionIds: [],
  },
  {
    id: 17,
    name: "Dim Sum Palace",
    cuisineId: 3,
    priceRange: "$$$",
    rating: 4.8,
    delivery: false,
    dietaryOptionIds: [3],
  },
  {
    id: 18,
    name: "Curry Club",
    cuisineId: 8,
    priceRange: "$",
    rating: 4.2,
    delivery: true,
    dietaryOptionIds: [3, 2, 1],
  },
  {
    id: 19,
    name: "Tapas Bar",
    cuisineId: 17,
    priceRange: "$$$",
    rating: 4.6,
    delivery: false,
    dietaryOptionIds: [3, 1],
  },
  {
    id: 20,
    name: "Pho Station",
    cuisineId: 21,
    priceRange: "$",
    rating: 4.4,
    delivery: true,
    dietaryOptionIds: [3, 1],
  },
  {
    id: 21,
    name: "Pasta Amore",
    cuisineId: 9,
    priceRange: "$$",
    rating: 4.3,
    delivery: true,
    dietaryOptionIds: [3],
  },
  {
    id: 22,
    name: "Fish Market",
    cuisineId: 16,
    priceRange: "$$$$",
    rating: 4.7,
    delivery: false,
    dietaryOptionIds: [1],
  },
  {
    id: 23,
    name: "Falafel Corner",
    cuisineId: 14,
    priceRange: "$",
    rating: 4.5,
    delivery: true,
    dietaryOptionIds: [3, 2],
  },
  {
    id: 24,
    name: "Biergarten",
    cuisineId: 5,
    priceRange: "$$$",
    rating: 4.2,
    delivery: false,
    dietaryOptionIds: [3],
  },
  {
    id: 25,
    name: "Noodle Bar",
    cuisineId: 3,
    priceRange: "$",
    rating: 4.0,
    delivery: true,
    dietaryOptionIds: [3, 2],
  },
  {
    id: 26,
    name: "Crepe Cafe",
    cuisineId: 4,
    priceRange: "$$",
    rating: 4.4,
    delivery: false,
    dietaryOptionIds: [3, 1],
  },
  {
    id: 27,
    name: "Tandoori Nights",
    cuisineId: 8,
    priceRange: "$$",
    rating: 4.7,
    delivery: true,
    dietaryOptionIds: [3, 2, 1],
  },
  {
    id: 28,
    name: "Samba Grill",
    cuisineId: 2,
    priceRange: "$$$",
    rating: 4.6,
    delivery: false,
    dietaryOptionIds: [1],
  },
  {
    id: 29,
    name: "Poke Bowl",
    cuisineId: 7,
    priceRange: "$$",
    rating: 4.5,
    delivery: true,
    dietaryOptionIds: [3, 1],
  },
  {
    id: 30,
    name: "Shawarma Express",
    cuisineId: 14,
    priceRange: "$",
    rating: 4.3,
    delivery: true,
    dietaryOptionIds: [3],
  },
  {
    id: 31,
    name: "Trattoria Bella",
    cuisineId: 9,
    priceRange: "$$$",
    rating: 4.8,
    delivery: false,
    dietaryOptionIds: [3, 1],
  },
  {
    id: 32,
    name: "Wing Stop",
    cuisineId: 1,
    priceRange: "$",
    rating: 3.9,
    delivery: true,
    dietaryOptionIds: [],
  },
  {
    id: 33,
    name: "Paella House",
    cuisineId: 17,
    priceRange: "$$$",
    rating: 4.5,
    delivery: false,
    dietaryOptionIds: [1],
  },
  {
    id: 34,
    name: "Bento Box",
    cuisineId: 10,
    priceRange: "$$",
    rating: 4.2,
    delivery: true,
    dietaryOptionIds: [3],
  },
  {
    id: 35,
    name: "Dumpling Dynasty",
    cuisineId: 3,
    priceRange: "$$",
    rating: 4.6,
    delivery: true,
    dietaryOptionIds: [3],
  },
  {
    id: 36,
    name: "Gyro Palace",
    cuisineId: 6,
    priceRange: "$",
    rating: 4.1,
    delivery: true,
    dietaryOptionIds: [3],
  },
  {
    id: 37,
    name: "Bistro Moderne",
    cuisineId: 4,
    priceRange: "$$$$",
    rating: 4.9,
    delivery: false,
    dietaryOptionIds: [3, 1],
  },
  {
    id: 38,
    name: "Pad Thai Station",
    cuisineId: 18,
    priceRange: "$$",
    rating: 4.4,
    delivery: true,
    dietaryOptionIds: [3, 2, 1],
  },
  {
    id: 39,
    name: "Lobster Shack",
    cuisineId: 16,
    priceRange: "$$$",
    rating: 4.7,
    delivery: false,
    dietaryOptionIds: [1],
  },
  {
    id: 40,
    name: "Burrito Loco",
    cuisineId: 13,
    priceRange: "$",
    rating: 4.0,
    delivery: true,
    dietaryOptionIds: [3, 2],
  },
  {
    id: 41,
    name: "Kebab Kingdom",
    cuisineId: 19,
    priceRange: "$$",
    rating: 4.3,
    delivery: true,
    dietaryOptionIds: [3],
  },
  {
    id: 42,
    name: "Bibimbap Bar",
    cuisineId: 11,
    priceRange: "$$",
    rating: 4.5,
    delivery: true,
    dietaryOptionIds: [3, 2],
  },
  {
    id: 43,
    name: "Cajun Kitchen",
    cuisineId: 1,
    priceRange: "$$$",
    rating: 4.4,
    delivery: false,
    dietaryOptionIds: [1],
  },
  {
    id: 44,
    name: "Momo House",
    cuisineId: 15,
    priceRange: "$",
    rating: 4.6,
    delivery: true,
    dietaryOptionIds: [3, 2],
  },
  {
    id: 45,
    name: "Croissant Cafe",
    cuisineId: 4,
    priceRange: "$$",
    rating: 4.3,
    delivery: false,
    dietaryOptionIds: [3],
  },
  {
    id: 46,
    name: "Wok Express",
    cuisineId: 3,
    priceRange: "$",
    rating: 3.8,
    delivery: true,
    dietaryOptionIds: [3],
  },
  {
    id: 47,
    name: "Pulled Pork Palace",
    cuisineId: 1,
    priceRange: "$$",
    rating: 4.2,
    delivery: true,
    dietaryOptionIds: [],
  },
  {
    id: 48,
    name: "Masala Magic",
    cuisineId: 8,
    priceRange: "$$$",
    rating: 4.8,
    delivery: false,
    dietaryOptionIds: [3, 2, 1],
  },
  {
    id: 49,
    name: "Sashimi Spot",
    cuisineId: 10,
    priceRange: "$$$$",
    rating: 4.9,
    delivery: false,
    dietaryOptionIds: [1],
  },
  {
    id: 50,
    name: "Taco Truck",
    cuisineId: 13,
    priceRange: "$",
    rating: 4.4,
    delivery: true,
    dietaryOptionIds: [3, 2, 1],
  },
];

export type Cuisine = {
  id: number;
  name: string;
};

export const cuisines: Cuisine[] = [
  { id: 1, name: "American" },
  { id: 2, name: "Brazilian" },
  { id: 3, name: "Chinese" },
  { id: 4, name: "French" },
  { id: 5, name: "German" },
  { id: 6, name: "Greek" },
  { id: 7, name: "Hawaiian" },
  { id: 8, name: "Indian" },
  { id: 9, name: "Italian" },
  { id: 10, name: "Japanese" },
  { id: 11, name: "Korean" },
  { id: 12, name: "Mediterranean" },
  { id: 13, name: "Mexican" },
  { id: 14, name: "Middle Eastern" },
  { id: 15, name: "Nepalese" },
  { id: 16, name: "Seafood" },
  { id: 17, name: "Spanish" },
  { id: 18, name: "Thai" },
  { id: 19, name: "Turkish" },
  { id: 20, name: "Vegan" },
  { id: 21, name: "Vietnamese" },
];

export type DietaryOption = {
  id: number;
  name: string;
};

export const dietaryOptions: DietaryOption[] = [
  { id: 1, name: "Gluten-Free" },
  { id: 2, name: "Vegan" },
  { id: 3, name: "Vegetarian" },
];
